#!/usr/bin/env bash
set -eu

rm -f "$HOME/.ssh/authorized_keys"
rm -f "$HOME/.tmux.conf"
rm -f "$HOME/.zshrc"
rm -f "$HOME/.zlogout"
rm -f "$HOME/.vimrc"
rm -f "$HOME/.vimrc_ide"
rm -f "$HOME/.bash_profile"
rm -f "$HOME/.bashrc"
rm -f "$HOME/.SpaceVim.d/init.toml"
rm -f "$HOME/.SpaceVim.d/autoload/myspacevim.vim"

rm -rf "$HOME/.terminfo"
rm -rf "$HOME/.vim"
rm -rf "$HOME/.fonts"
rm -rf "$HOME/.config/nvim"
rm -rf "$HOME/.SpaceVim"
rm -rf "$HOME/.cache/SpaceVim"
rm -rf "$HOME/.cache/vimfiles"
rm -rf "$HOME/.tmux"

rm -rf "$HOME/.local/share/nvim/plugged"
rm -rf "$HOME/.local/share/nvim/site/autoload/plug.vim"
