#!/usr/bin/env bash

if [ ! -d "$HOME/.ssh" ]; then
   mkdir $HOME/.ssh
   chmod 700 $HOME/.ssh
fi

# we may have to fix .dotfiles/ssh permissions
chmod 700 ~/.dotfiles
chmod 700 ~/.dotfiles/ssh
chmod 644 ~/.dotfiles/ssh/authorized_keys

[ ! -e "$HOME/.ssh/authorized_keys" ] && ln -s $HOME/.dotfiles/ssh/authorized_keys $HOME/.ssh/authorized_keys
[ ! -e "$HOME/.tmux.conf" ] && ln -s $HOME/.dotfiles/tmux.conf $HOME/.tmux.conf
[ ! -e "$HOME/.zshrc" ] && ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc
[ ! -e "$HOME/.vimrc" ] && ln -s $HOME/.dotfiles/vim/vimrc $HOME/.vimrc
[ ! -e "$HOME/.vim" ] && ln -s $HOME/.dotfiles/vim $HOME/.vim
[ ! -e "$HOME/.fonts" ] && ln -s $HOME/.dotfiles/fonts $HOME/.fonts

cd $HOME/.dotfiles
git submodule init
git submodule update
git submodule foreach git pull origin master

# Fix oh-my-zsh on older zsh versions
if (zsh --version | grep -q 4.2); then
  cd $HOME/.dotfiles/zsh/oh-my-zsh
  git checkout e3cede37a0 -- lib/termsupport.zsh
  cd $HOME/.dotfiles
fi

VIMVERSION=$(vim -u -e -T dumb --cmd 'exe "set t_cm=\<C-M>"|echo v:version|quit'|tr -d '\015')

if [ "$VIMVERSION" -ge "703" ]; then
  pushd ~/.dotfiles/vim/bundle/YouCompleteMe
  git submodule update --init --recursive
  ./install.sh --clang-completer
  popd
fi

fc-cache -vf ~/.fonts
