#! /usr/bin/env bash
set -eu

if [[ ! -d "$HOME/.ssh" ]]; then
  mkdir "$HOME/.ssh"
  chmod 700 "$HOME/.ssh"
fi

# we may have to fix .dotfiles/ssh permissions
chmod 700 "$HOME/.dotfiles"
chmod 700 "$HOME/.dotfiles/ssh"
chmod 644 "$HOME/.dotfiles/ssh/authorized_keys"

mkdir -p "$HOME/.config/nvim"
mkdir -p "$HOME/.SpaceVim.d/autoload"

declare -A links
links["$HOME/.ssh/authorized_keys"]="$HOME/.dotfiles/ssh/authorized_keys"
links["$HOME/.tmux.conf"]="$HOME/.dotfiles/tmux/tmux.conf"
links["$HOME/.zshrc"]="$HOME/.dotfiles/zsh/zshrc"
links["$HOME/.zlogout"]="$HOME/.dotfiles/zsh/zlogout"
links["$HOME/.config/nvim/init.vim"]="$HOME/.dotfiles/nvim/init.vim"
links["$HOME/.SpaceVim.d/init.toml"]="$HOME/.dotfiles/SpaceVim/init.toml"
links["$HOME/.SpaceVim.d/autoload/myspacevim.vim"]="$HOME/.dotfiles/SpaceVim/autoload/myspacevim.vim"
for f in "${!links[@]}"; do [[ -e $f ]] || ln -s "${links[$f]}" "$f"; done

git submodule update
cd "$HOME/.dotfiles"
git submodule init
git submodule update

git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"

# Fix oh-my-zsh on older zsh versions
if (zsh --version | grep -q 4.2); then
  cd "$HOME/.dotfiles/zsh/oh-my-zsh"
  git checkout e3cede37a0 -- lib/termsupport.zsh
  cd "$HOME/.dotfiles"
fi
