#! /usr/bin/env bash
set -eu

if [[ ! -d "$HOME/.ssh" ]]; then
  mkdir "$HOME/.ssh"
  chmod 700 "$HOME/.ssh"
fi

# we may have to fix .dotfiles/ssh permissions
chmod 700 "$HOME/.dotfiles"
chmod 700 "$HOME/.dotfiles/ssh"
chmod 644 "$HOME/.dotfiles/ssh/authorized_keys"

declare -A links
links["$HOME/.ssh/authorized_keys"]="$HOME/.dotfiles/ssh/authorized_keys"
links["$HOME/.tmux.conf"]="$HOME/.dotfiles/tmux/tmux.conf"
links["$HOME/.config/nvim"]="$HOME/.dotfiles/nvim"
links["$HOME/.config/fish"]="$HOME/.dotfiles/fish"
for f in "${!links[@]}"; do [[ -e $f ]] || ln -s "${links[$f]}" "$f"; done

cd "$HOME/.dotfiles"
git submodule init
git submodule update

git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"

nvim -cq
