#! /usr/bin/env bash
set -eu

which make >/dev/null 2>&1 || {
  echo "Error:  Please instll make"
  exit 1
}

which gcc >/dev/null 2>&1 || {
  echo "Error:  Please instll gcc"
  exit 1
}

if [[ -d $HOME/.SpaceVim ]]; then
  cd "$HOME/.SpaceVim"
  git pull
else
  git clone --depth=1 https://github.com/SpaceVim/SpaceVim.git \
    "$HOME/.SpaceVim"
fi
