alias ls='ls --color=auto'
alias vi='nvim'
alias vim='nvim'
alias vimdiff='nvim -d'
alias ide='vim -s ~/.vimrc_ide'
alias unix2dos='dos2unix --u2d'
alias 7zip='7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on'
alias pass='apg -a1 -n1 -m 12'
alias lockscreen='xscreensaver-command -lock'
alias rmove='ionice -c 3 rsync -rv --progress --inplace --remove-source-files'
cp --reflink=always --version >/dev/null 2>&1 && alias cp='cp --reflink=auto'
alias gitsub='git submodule update --init --recursive'
alias gitup='git submodule update --init --recursive && git submodule foreach --recursive git pull origin master'
alias rvmget='\curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles'
alias pantera-up="wol bc:5f:f4:af:b2:14"
