ZSH=$HOME/.dotfiles/zsh/oh-my-zsh

# Older zsh needs different prompt
if (zsh --version | grep -q 4.2); then
  ZSH_THEME="gentoo"
else
  ZSH_THEME="agnoster"
fi

[ grep --exclude-dir=test test /dev/null 2>/dev/null ] || grep_old=true

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy/mm/dd"
CASE_SENSITIVE="true"
plugins=(git tmux vi-mode)
source $ZSH/oh-my-zsh.sh

# User configuration

# Old versions of grep don't accept --exclude-dir so unset GREP_OPTIONS
[[ $grep_old = "true" ]] && unset GREP_OPTIONS

HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=50000

export EDITOR="vim"
export MAIL=$HOME/Mail/inbox

source ~/.dotfiles/zsh/paths
source ~/.dotfiles/zsh/aliases
source ~/.dotfiles/zsh/quirks
source ~/.dotfiles/zsh/mancolors
source ~/.dotfiles/zsh/dircolors
source ~/.dotfiles/zsh/bindings

if [ -f ~/.localrc ]; then
  . ~/.localrc
fi
