ZSH=$HOME/.dotfiles/zsh/oh-my-zsh
ZSH_THEME="agnoster"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy/mm/dd"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# User configuration

HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=50000

export EDITOR="vim"
export MAIL=$HOME/Mail/inbox

source ~/.dotfiles/zsh/paths
source ~/.dotfiles/zsh/aliases
source ~/.dotfiles/zsh/quirks
source ~/.dotfiles/zsh/mancolors
source ~/.dotfiles/zsh/dircolors
