ZSH=$HOME/.dotfiles/zsh/oh-my-zsh
ZSH_CUSTOM="$HOME/.dotfiles/zsh/oh-my-zsh-custom"

ZSH_THEME="gruvbox-dark"

grep --exclude-dir=test --version >/dev/null 2>&1 || grep_old=true

DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy/mm/dd"
CASE_SENSITIVE="true"
ZSH_DISABLE_COMPFIX="true"
plugins=(git tmux vi-mode svn)
source $ZSH/oh-my-zsh.sh
setopt auto_name_dirs

# User configuration

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# Old versions of grep don't accept --exclude-dir so unset GREP_OPTIONS
[[ $grep_old == "true" ]] && unset GREP_OPTIONS

HISTFILE=~/.histfile
HISTSIZE=50000
SAVEHIST=50000

export EDITOR="nvim"
export MAIL=$HOME/Mail/inbox

source ~/.dotfiles/zsh/paths
source ~/.dotfiles/zsh/aliases
source ~/.dotfiles/zsh/quirks
source ~/.dotfiles/zsh/mancolors
source ~/.dotfiles/zsh/dircolors
source ~/.dotfiles/zsh/bindings
source ~/.dotfiles/zsh/ruby

[[ -f ~/.localrc ]] && . ~/.localrc

true
